import time
from selenium import webdriver
driver = webdriver.Chrome('chromedriver.exe')
driver.get('http://newtours.demoaut.com/')
time.sleep(2)
user_box = driver.find_element_by_name('userName').send_keys("test2")
pass_box = driver.find_element_by_name('password').send_keys("test4")
submit_button = driver.find_element_by_name('login')
#user_box.send_keys('test')
#pass_box.send_keys('test')
submit_button.click()
time.sleep(2)
button = driver.find_element_by_xpath("//tr[2]/td/table/tbody/tr/td[2]/a").click()
time.sleep(4)
driver.find_element_by_name("firstName").send_keys("andres")
driver.find_element_by_name("lastName").send_keys("pacheco")
driver.find_element_by_name("phone").send_keys(31234567)
driver.find_element_by_name("userName").send_keys("andres.pacheco@.io")
time.sleep(4)
driver.quit()
